create table if not exists public.lesson_mentor_notes (
  id bigint generated by default as identity primary key,
  student_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null,
  lesson_id text not null,
  title text not null default 'MentorLM note',
  body text not null,
  created_by text not null default 'mentorlm',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint lesson_mentor_notes_created_by_check check (created_by = 'mentorlm'),
  constraint lesson_mentor_notes_has_body check (length(btrim(body)) > 0)
);

create index if not exists lesson_mentor_notes_student_lesson_idx
  on public.lesson_mentor_notes (student_id, course_id, lesson_id, created_at desc);

alter table public.lesson_mentor_notes enable row level security;

drop policy if exists "Students can read own lesson MentorLM notes" on public.lesson_mentor_notes;
create policy "Students can read own lesson MentorLM notes"
  on public.lesson_mentor_notes
  for select
  to authenticated
  using ((select auth.uid()) = student_id);

drop policy if exists "Students can insert own lesson MentorLM notes" on public.lesson_mentor_notes;
create policy "Students can insert own lesson MentorLM notes"
  on public.lesson_mentor_notes
  for insert
  to authenticated
  with check ((select auth.uid()) = student_id);

drop policy if exists "Students can update own lesson MentorLM notes" on public.lesson_mentor_notes;
create policy "Students can update own lesson MentorLM notes"
  on public.lesson_mentor_notes
  for update
  to authenticated
  using ((select auth.uid()) = student_id)
  with check ((select auth.uid()) = student_id);

drop policy if exists "Students can delete own lesson MentorLM notes" on public.lesson_mentor_notes;
create policy "Students can delete own lesson MentorLM notes"
  on public.lesson_mentor_notes
  for delete
  to authenticated
  using ((select auth.uid()) = student_id);

drop trigger if exists lesson_mentor_notes_set_updated_at on public.lesson_mentor_notes;
create trigger lesson_mentor_notes_set_updated_at
  before update on public.lesson_mentor_notes
  for each row
  execute function public.set_updated_at();

grant select, insert, update, delete on table public.lesson_mentor_notes to authenticated;
grant usage, select on sequence public.lesson_mentor_notes_id_seq to authenticated;
grant all on table public.lesson_mentor_notes to service_role;
grant all on sequence public.lesson_mentor_notes_id_seq to service_role;
