do $$
begin
  if to_regclass('public.mentor_lm_lesson_notes') is null
    and to_regclass('public.lesson_mentor_notes') is not null then
    alter table public.lesson_mentor_notes rename to mentor_lm_lesson_notes;

    if exists (
      select 1
      from pg_class
      where relname = 'lesson_mentor_notes_id_seq'
        and relkind = 'S'
    ) then
      alter sequence public.lesson_mentor_notes_id_seq rename to mentor_lm_lesson_notes_id_seq;
    end if;

    if exists (
      select 1
      from pg_class
      where relname = 'lesson_mentor_notes_student_lesson_idx'
        and relkind = 'i'
    ) then
      alter index public.lesson_mentor_notes_student_lesson_idx rename to mentor_lm_lesson_notes_student_lesson_idx;
    end if;
  end if;
end $$;

create table if not exists public.student_course_enrollments (
  id bigint generated by default as identity primary key,
  student_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null,
  status text not null default 'active',
  progress_percent numeric(5,2) not null default 0,
  enrolled_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint student_course_enrollments_status_check check (status in ('active', 'paused', 'completed', 'archived')),
  constraint student_course_enrollments_progress_check check (progress_percent >= 0 and progress_percent <= 100),
  constraint student_course_enrollments_student_course_key unique (student_id, course_id)
);

create table if not exists public.student_opportunities (
  id bigint generated by default as identity primary key,
  student_id uuid not null references auth.users(id) on delete cascade,
  opportunity_id text not null,
  status text not null default 'saved',
  source text not null default 'search',
  saved_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint student_opportunities_status_check check (status in ('saved', 'chosen')),
  constraint student_opportunities_source_check check (source in ('search', 'recommended-window', 'manual')),
  constraint student_opportunities_student_opportunity_key unique (student_id, opportunity_id)
);

create table if not exists public.student_workspace_state (
  student_id uuid primary key references auth.users(id) on delete cascade,
  recommended_opportunities_dismissed boolean not null default false,
  recommended_opportunities_dismissed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mentor_lm_lesson_notes (
  id bigint generated by default as identity primary key,
  student_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null,
  lesson_id text not null,
  title text not null default 'MentorLM note',
  body text not null,
  created_by text not null default 'mentorlm',
  is_hidden boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint mentor_lm_lesson_notes_created_by_check check (created_by = 'mentorlm'),
  constraint mentor_lm_lesson_notes_has_body check (length(btrim(body)) > 0)
);

alter table public.mentor_lm_lesson_notes
  add column if not exists is_hidden boolean not null default false;

create index if not exists student_course_enrollments_student_idx
  on public.student_course_enrollments (student_id, status, enrolled_at desc);

create index if not exists student_opportunities_student_idx
  on public.student_opportunities (student_id, status, saved_at desc);

create index if not exists mentor_lm_lesson_notes_student_lesson_idx
  on public.mentor_lm_lesson_notes (student_id, course_id, lesson_id, is_hidden, created_at desc);

alter table public.student_course_enrollments enable row level security;
alter table public.student_opportunities enable row level security;
alter table public.student_workspace_state enable row level security;
alter table public.mentor_lm_lesson_notes enable row level security;

drop policy if exists "Students can read own course enrollments" on public.student_course_enrollments;
create policy "Students can read own course enrollments"
  on public.student_course_enrollments
  for select
  to authenticated
  using ((select auth.uid()) = student_id);

drop policy if exists "Students can insert own course enrollments" on public.student_course_enrollments;
create policy "Students can insert own course enrollments"
  on public.student_course_enrollments
  for insert
  to authenticated
  with check ((select auth.uid()) = student_id);

drop policy if exists "Students can update own course enrollments" on public.student_course_enrollments;
create policy "Students can update own course enrollments"
  on public.student_course_enrollments
  for update
  to authenticated
  using ((select auth.uid()) = student_id)
  with check ((select auth.uid()) = student_id);

drop policy if exists "Students can read own opportunities" on public.student_opportunities;
create policy "Students can read own opportunities"
  on public.student_opportunities
  for select
  to authenticated
  using ((select auth.uid()) = student_id);

drop policy if exists "Students can insert own opportunities" on public.student_opportunities;
create policy "Students can insert own opportunities"
  on public.student_opportunities
  for insert
  to authenticated
  with check ((select auth.uid()) = student_id);

drop policy if exists "Students can update own opportunities" on public.student_opportunities;
create policy "Students can update own opportunities"
  on public.student_opportunities
  for update
  to authenticated
  using ((select auth.uid()) = student_id)
  with check ((select auth.uid()) = student_id);

drop policy if exists "Students can read own workspace state" on public.student_workspace_state;
create policy "Students can read own workspace state"
  on public.student_workspace_state
  for select
  to authenticated
  using ((select auth.uid()) = student_id);

drop policy if exists "Students can insert own workspace state" on public.student_workspace_state;
create policy "Students can insert own workspace state"
  on public.student_workspace_state
  for insert
  to authenticated
  with check ((select auth.uid()) = student_id);

drop policy if exists "Students can update own workspace state" on public.student_workspace_state;
create policy "Students can update own workspace state"
  on public.student_workspace_state
  for update
  to authenticated
  using ((select auth.uid()) = student_id)
  with check ((select auth.uid()) = student_id);

drop policy if exists "Students can read own lesson MentorLM notes" on public.mentor_lm_lesson_notes;
drop policy if exists "Students can read own MentorLM lesson notes" on public.mentor_lm_lesson_notes;
create policy "Students can read own MentorLM lesson notes"
  on public.mentor_lm_lesson_notes
  for select
  to authenticated
  using ((select auth.uid()) = student_id);

drop policy if exists "Students can insert own lesson MentorLM notes" on public.mentor_lm_lesson_notes;
drop policy if exists "Students can insert own MentorLM lesson notes" on public.mentor_lm_lesson_notes;
create policy "Students can insert own MentorLM lesson notes"
  on public.mentor_lm_lesson_notes
  for insert
  to authenticated
  with check ((select auth.uid()) = student_id);

drop policy if exists "Students can update own lesson MentorLM notes" on public.mentor_lm_lesson_notes;
drop policy if exists "Students can update own MentorLM lesson notes" on public.mentor_lm_lesson_notes;
create policy "Students can update own MentorLM lesson notes"
  on public.mentor_lm_lesson_notes
  for update
  to authenticated
  using ((select auth.uid()) = student_id)
  with check ((select auth.uid()) = student_id);

drop trigger if exists student_course_enrollments_set_updated_at on public.student_course_enrollments;
create trigger student_course_enrollments_set_updated_at
  before update on public.student_course_enrollments
  for each row
  execute function public.set_updated_at();

drop trigger if exists student_opportunities_set_updated_at on public.student_opportunities;
create trigger student_opportunities_set_updated_at
  before update on public.student_opportunities
  for each row
  execute function public.set_updated_at();

drop trigger if exists student_workspace_state_set_updated_at on public.student_workspace_state;
create trigger student_workspace_state_set_updated_at
  before update on public.student_workspace_state
  for each row
  execute function public.set_updated_at();

drop trigger if exists lesson_mentor_notes_set_updated_at on public.mentor_lm_lesson_notes;
drop trigger if exists mentor_lm_lesson_notes_set_updated_at on public.mentor_lm_lesson_notes;
create trigger mentor_lm_lesson_notes_set_updated_at
  before update on public.mentor_lm_lesson_notes
  for each row
  execute function public.set_updated_at();

grant select, insert, update on table public.student_course_enrollments to authenticated;
grant select, insert, update on table public.student_opportunities to authenticated;
grant select, insert, update on table public.student_workspace_state to authenticated;
grant select, insert, update on table public.mentor_lm_lesson_notes to authenticated;

grant usage, select on sequence public.student_course_enrollments_id_seq to authenticated;
grant usage, select on sequence public.student_opportunities_id_seq to authenticated;
grant usage, select on sequence public.mentor_lm_lesson_notes_id_seq to authenticated;

grant all on table public.student_course_enrollments to service_role;
grant all on table public.student_opportunities to service_role;
grant all on table public.student_workspace_state to service_role;
grant all on table public.mentor_lm_lesson_notes to service_role;

grant all on sequence public.student_course_enrollments_id_seq to service_role;
grant all on sequence public.student_opportunities_id_seq to service_role;
grant all on sequence public.mentor_lm_lesson_notes_id_seq to service_role;
