create table if not exists public.telegram_ingest_events (
  id bigint generated by default as identity primary key,
  source_id text not null,
  payload_type text not null,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'received',
  target_table text,
  target_id text,
  error_message text,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint telegram_ingest_events_source_key unique (source_id),
  constraint telegram_ingest_events_payload_type_check check (payload_type in ('deadline', 'opportunity', 'course')),
  constraint telegram_ingest_events_status_check check (status in ('received', 'processed', 'failed'))
);

create table if not exists public.telegram_course_announcements (
  id text primary key,
  source_id text not null,
  title text not null,
  description text not null default '',
  course_title text,
  deadline text,
  starts_at text,
  apply_url text not null default '',
  tags jsonb not null default '[]'::jsonb,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint telegram_course_announcements_source_key unique (source_id),
  constraint telegram_course_announcements_status_check check (status in ('draft', 'imported', 'archived')),
  constraint telegram_course_announcements_has_title check (length(btrim(title)) > 0)
);

create index if not exists telegram_ingest_events_status_received_idx
  on public.telegram_ingest_events (status, received_at desc);

create index if not exists telegram_course_announcements_status_created_idx
  on public.telegram_course_announcements (status, created_at desc);

alter table public.telegram_ingest_events enable row level security;
alter table public.telegram_course_announcements enable row level security;

drop policy if exists "Staff can read Telegram ingest events" on public.telegram_ingest_events;
create policy "Staff can read Telegram ingest events"
  on public.telegram_ingest_events
  for select
  to authenticated
  using (private.is_admin_member(array['admin', 'mentor', 'content_editor']));

drop policy if exists "Staff can read Telegram course announcements" on public.telegram_course_announcements;
create policy "Staff can read Telegram course announcements"
  on public.telegram_course_announcements
  for select
  to authenticated
  using (private.is_admin_member(array['admin', 'mentor', 'content_editor']));

drop policy if exists "Editors can update Telegram course announcements" on public.telegram_course_announcements;
create policy "Editors can update Telegram course announcements"
  on public.telegram_course_announcements
  for update
  to authenticated
  using (private.is_admin_member(array['admin', 'content_editor']))
  with check (private.is_admin_member(array['admin', 'content_editor']));

drop trigger if exists telegram_ingest_events_set_updated_at on public.telegram_ingest_events;
create trigger telegram_ingest_events_set_updated_at
  before update on public.telegram_ingest_events
  for each row
  execute function public.set_updated_at();

drop trigger if exists telegram_course_announcements_set_updated_at on public.telegram_course_announcements;
create trigger telegram_course_announcements_set_updated_at
  before update on public.telegram_course_announcements
  for each row
  execute function public.set_updated_at();

grant select on table public.telegram_ingest_events to authenticated;
grant select, update on table public.telegram_course_announcements to authenticated;
grant all on table public.telegram_ingest_events to service_role;
grant all on table public.telegram_course_announcements to service_role;
grant usage, select on sequence public.telegram_ingest_events_id_seq to service_role;
