create table if not exists public.lesson_assignment_submissions (
  id bigint generated by default as identity primary key,
  student_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null,
  lesson_id text not null,
  answer text not null default '',
  attachment_path text,
  attachment_name text,
  submitted_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint lesson_assignment_submissions_current_key unique (student_id, course_id, lesson_id),
  constraint lesson_assignment_submissions_has_content check (
    length(btrim(answer)) > 0 or attachment_path is not null
  )
);

alter table public.lesson_assignment_submissions enable row level security;

drop policy if exists "Students can read own lesson assignment submissions" on public.lesson_assignment_submissions;
create policy "Students can read own lesson assignment submissions"
  on public.lesson_assignment_submissions
  for select
  to authenticated
  using ((select auth.uid()) = student_id);

drop policy if exists "Students can insert own lesson assignment submissions" on public.lesson_assignment_submissions;
create policy "Students can insert own lesson assignment submissions"
  on public.lesson_assignment_submissions
  for insert
  to authenticated
  with check ((select auth.uid()) = student_id);

drop policy if exists "Students can update own lesson assignment submissions" on public.lesson_assignment_submissions;
create policy "Students can update own lesson assignment submissions"
  on public.lesson_assignment_submissions
  for update
  to authenticated
  using ((select auth.uid()) = student_id)
  with check ((select auth.uid()) = student_id);

drop trigger if exists lesson_assignment_submissions_set_updated_at on public.lesson_assignment_submissions;
create trigger lesson_assignment_submissions_set_updated_at
  before update on public.lesson_assignment_submissions
  for each row
  execute function public.set_updated_at();

grant select, insert, update on table public.lesson_assignment_submissions to authenticated;
grant usage, select on sequence public.lesson_assignment_submissions_id_seq to authenticated;
grant all on table public.lesson_assignment_submissions to service_role;
grant all on sequence public.lesson_assignment_submissions_id_seq to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'lesson-assignment-attachments',
  'lesson-assignment-attachments',
  false,
  10485760,
  array[
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'text/plain',
    'image/png',
    'image/jpeg'
  ]::text[]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Students can upload own lesson assignment attachments" on storage.objects;
create policy "Students can upload own lesson assignment attachments"
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'lesson-assignment-attachments'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );

drop policy if exists "Students can read own lesson assignment attachments" on storage.objects;
create policy "Students can read own lesson assignment attachments"
  on storage.objects
  for select
  to authenticated
  using (
    bucket_id = 'lesson-assignment-attachments'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );
